# 配置文件


#微信接口调用配置
userService:
  url: https://api.weixin.qq.com/sns/jscode2session?appid={1}&secret={2}&js_code={3}&grant_type={4}
  appid:
  SECRET: secret
  grantType: authorization_code

#数据源
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
    url: jdbc:mysql://localhost:3306/book_manage?useUnicode=true&characterEncoding=utf8
    username: student
    password: 1234567
#mybatis配置
mybatis:
  mapper-locations:
  type-aliases-package:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#jwt的配置
JWT:
  secret: feichang6and1
  expiration: 1800


logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.miniapp: debug
    cn.binarywang.wx.miniapp: debug
wx:
  miniapp:
    configs:
      - appid: wxe66c8a3fab1d8cfd
        secret: 77d166b4b4d32d8cb12a4067c7b853d9
        token: token
        aesKey:
        msgDataFormat: JSON


